### ISSUE TITLE
WAIT PLS READ 3THAN

### ISSUE THREAD

**Issue by Lux-14** [ataridiscord/Roblox#2]
Hey Ethan, you know what they say, "friendship isn't a bed of roses, it's more like a bed of Legos - painful, but worth the fun." So let's put our differences aside and rebuild our friendship brick by brick. I promise not to step on your toes again, or your Legos for that matter. Give me one more chance, friend!

**Comment by ataridiscord** [comment]
Request Emiray to add me to that group chat, I'll leave without warning if necessary.
